# Use root/mysql as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql

  adminer:
    image: docker.io/victorromero/com.mx.fintecheando.mifosx.17.07.01
    restart: always
    ports:
      - 8080:8080